AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloud-Native Portfolio Website Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']
  
  DomainName:
    Type: String
    Description: 'Domain name for the portfolio website'
    Default: 'your-portfolio.com'

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './vpc.yaml'
      Parameters:
        Environment: !Ref Environment

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './ecs.yaml'
      Parameters:
        Environment: !Ref Environment
        VPC: !GetAtt VPCStack.Outputs.VPC
        PrivateSubnets: !GetAtt VPCStack.Outputs.PrivateSubnets
        PublicSubnets: !GetAtt VPCStack.Outputs.PublicSubnets

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './alb.yaml'
      Parameters:
        Environment: !Ref Environment
        VPC: !GetAtt VPCStack.Outputs.VPC
        PublicSubnets: !GetAtt VPCStack.Outputs.PublicSubnets
        ECSSecurityGroup: !GetAtt ECSStack.Outputs.ECSSecurityGroup

Outputs:
  LoadBalancerURL:
    Description: 'URL of the load balancer'
    Value: !GetAtt ALBStack.Outputs.LoadBalancerURL
    Export:
      Name: !Sub '${AWS::StackName}-LoadBalancerURL'