version: '3.8'

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    restart: unless-stopped

  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=8080
    restart: unless-stopped

  # Optional: Local MongoDB if you don't want to use a cloud service
  # mongo:
  #   image: mongo:7
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   environment:
  #     - MONGO_INITDB_DATABASE=portfolio
  #   restart: unless-stopped

# volumes:
#   mongo_data: